[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "APSIM_RotationTraining"
authors = [{name = "Uwe Grewer", email = "uwe.grewer@unisq.edu.au"}]
dynamic = ["version", "description"]
